server:
  port: 8004

api-gateway-sdk:
  # 注册中心，从这里获取接口信息以及完成注册网关操作
  address: http://localhost:8001
  # 系统标识
  systemId: api-gateway-sdk-00
  systemName: 网关sdk测试工程
  systemRegistry: zookeeper:127.0.0.1:2181