server:
  port: 8082

dubbo:
  application:
    name: yuluo-api-gateway-test
    version: 1.0.0
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: indi.yuluo.gateway.rpc

api-gateway-sdk:
  # 注册中心，从这里获取接口信息以及完成注册网关操作
  address: http://localhost:8001
  # 系统标识
  systemId: api-gateway-sdk-00
  systemName: 网关sdk测试工程
  systemRegistry: zookeeper:127.0.0.1:2181